- name: Notify Slack
  hosts: localhost
  tasks:
  - name: httpd install
    yum:
      name: httpd
      state: present
    notify: installation_slack

  - name: httpd start
    service:
      name: httpd
      state: started
    notify: service_slack

  handlers:
  - name: installation_slack
    slack:
      domain: domain.slack.com
      token: "xxx/yyy/zzz"
      msg: "httpd installed"
      channel "#channel"
  - name: service_slack
    slack:
      domain: domain.slack.com
      token: "xxx/yyy/zzz"
      msg: "httpd restarted"
      channel "#channel"
